name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Updated to your .NET version

    - name: Install dependencies
      run: dotnet restore Sign-up.Solution/Sign-up/Sign-up.csproj

    - name: Build
      run: dotnet build Sign-up.Solution/Sign-up/Sign-up.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish Sign-up.Solution/Sign-up/Sign-up.csproj -c Release -o ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'My-Sign-up-App'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/publish
